### ISSUE TITLE
Running on Windows 7

### ISSUE THREAD

**Issue by Steviey** [kogosoftwarellc/run-react-native#2]
Hello.

I have set the env var accordingly set RUN_REACT_NATIVE_ANDROID_AVD='Nexus_4_API_23'

When I type in the project folder: run-react-native

I get as output: 'The system cannot find the path specified'. 

My Android stuff is on another partition noticed in the systems env vars.

Any suggestions?

Is it for Unix only?

**Comment by jsdevel** [comment]
Right now this is unix only.  You could run this with git bash or another alternative.  Or provide a .bat file.

**Comment by Steviey** [comment]
Thx.
